### ISSUE TITLE
Is this in a usable state?

### ISSUE THREAD

**Issue by kpfaulkner** [michaelansel/hubot-rbac#1]
Looking at Hubot permissions/role options. Have noticed this file but also plenty of Github issue threads. Am just wondering if the whole permissions/role issue with Hubot is now a solved problem?

**Comment by michaelansel** [comment]
This is waiting on github/hubot#803. Once that gets merged, I'm hoping to come back to this and build out a better framework. Without middleware, permissioning is far from a solved problem in Hubot.

**Comment by kpfaulkner** [comment]
Thanks for the details...  I'll temporarily put in a work around.
